swagger: "2.0"
info:
  version: "1.0.0"
  title: "User bets service"
host: "localhost"
basePath: "/sensedia-bet"
paths:
  /api/bet:
    post:
      tags:
      - "bets"
      summary: "Make a bet"
      description: ""
      operationId: "makeBet"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Bet"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid Bet"
    put:
      tags:
      - "bets"
      summary: "Update a bet"
      description: ""
      operationId: "updateBet"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Bet"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid Bet"
        404:
          description: "Bet not found"
definitions:
  Bet:
    type: "object"
    properties:
      matchId:
        type: "string"
      homeResult:
        type: "integer"
        format: "int32"
      awayResult:
        type: "integer"
        format: "int32"
