server:
  port: 9999
spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
  data:
    mongodb:
      database: "USER-BETS"
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
match:
  exchange: matches
  result:
    queue: result
    key: result
ranking:
  exchange: bets
  user:
    queue: points
    key: points
management:
  endpoints:
    web:
      exposure:
        include: "*"