server:
  port: 9999
  servlet:
    context-path: /user-bets
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: "USER-BETS"
      host: localhost
      port: 27017
match:
  exchange: matches
  result:
    queue: result
    key: result
ranking:
  exchange: bets
  user:
    queue: points
    key: points